package main.java.sys.rest.server.auction.messageTypes;

public enum MessageEnvelopeAuctionTypes {

	OPEN_AUCTION, 
	CLOSE_AUCTION,
	ADD_BID,
	LIST_ALL_AUCTIONS,
	LIST_OPENED_AUCTIONS,
	LIST_CLOSED_AUCTIONS,
	LIST_ALL_AUCTIONS_BY_OWNER,
	LIST_OPENED_AUCTIONS_BY_OWNER,
	LIST_CLOSED_AUCTIONS_BY_OWNER,
	LIST_ALL_AUCTIONS_BY_ID,
	LIST_OPENED_AUCTIONS_BY_ID,
	LIST_CLOSED_AUCTIONS_BY_ID,
	LIST_BIDS_OF_ALL_AUCTIONS_BY_AUCTION_ID,
	LIST_BIDS_OF_OPENED_AUCTIONS_BY_AUCTION_ID,
	LIST_BIDS_OF_CLOSED_AUCTIONS_BY_AUCTION_ID,
	LIST_BIDS_OF_ALL_AUCTIONS_BY_AUCTION_ID_AND_CLIENT_ID,
	LIST_BIDS_OF_OPENED_AUCTIONS_BY_AUCTION_ID_AND_CLIENT_ID,
	LIST_BIDS_OF_CLOSED_AUCTIONS_BY_AUCTION_ID_AND_CLIENT_ID,
	LIST_ALL_BIDS_BY_CLIENT_ID,
	LIST_OPENED_BIDS_BY_CLIENT_ID,
	LIST_CLOSED_BIDS_BY_CLIENT_ID,
	CHECK_OUTCOME_ALL_AUCTION,
	CHECK_OUTCOME_OPENED_AUCTION,
	CHECK_OUTCOME_CLOSED_AUCTION,
	CHECK_OUTCOME_ALL_AUCTION_ID,
	CHECK_OUTCOME_OPENED_AUCTION_ID,
	CHECK_OUTCOME_CLOSED_AUCTION_ID
}
